###
POST http://{{host}}:{{port}}/game
Content-Type: application/x-www-form-urlencoded

name=game333

###
// {"id":"ba7a9069-61d4-4d37-be4e-7ca19f8a4ac4","name":"game2","players":null,"score":0,"current_player_index":0}

###
GET http://{{host}}:{{port}}/game?id=ba7a9069-61d4-4d37-be4e-7ca19f8a4ac4

###
POST http://{{host}}:{{port}}/join_game
Content-Type: application/x-www-form-urlencoded

game_id=ba7a9069-61d4-4d37-be4e-7ca19f8a4ac4&player_id=7563062206492869000

###
POST http://{{host}}:{{port}}/start_game
Content-Type: application/x-www-form-urlencoded

game_id=ba7a9069-61d4-4d37-be4e-7ca19f8a4ac4


###
GET http://{{host}}:{{port}}/games