### List Games
GET http://{{host}}:{{port}}/games

### New Game
POST http://{{host}}:{{port}}/game
Content-Type: application/x-www-form-urlencoded

name=nice game

###
#{
#  "game_id": "g-dc0f974eff1517161d333f285de953eb"
#}

### Get Game Detail
GET http://{{host}}:{{port}}/game/g-dc0f974eff1517161d333f285de953eb

### Start Game
POST http://{{host}}:{{port}}/start_game
Content-Type: application/x-www-form-urlencoded

game_id=g-dc0f974eff1517161d333f285de953eb&player_id=p-6c792b64151617165d070c5b247506f7


### play card
POST http://{{host}}:{{port}}/play/g-dc0f974eff1517161d333f285de953eb/p-ccbe2294fd15171623b1ea8f1a95d3d7/2
Content-Type: application/json

{
  "rank_ace_change_next_player": "p-6c792b64151617165d070c5b247506f7"
}
